feat: connection to mongo database
aAnurag7/todoList pull request #4
Opened 2023-03-02 08:46 UTC by aAnurag7

used mongoose to  connect

2023-03-03 06:21 UTC, capedcrusader11 requested changes

2023-03-03 06:21 UTC, capedcrusader11 commented on server/DB/connection.js
> +
inconsistent indentation

2023-03-03 06:21 UTC, capedcrusader11 commented on server/index.js
> +app.post('/user/create',(req,res)=>{
inconsistent spacing

2023-03-03 06:21 UTC, capedcrusader11 commented on server/model/userSchema.js
> +  next();
There should not be any commented code when your PR is ready

2023-03-03 06:21 UTC, capedcrusader11 commented on server/router/auth.js
> +})
install prettier this looks very bad

2023-03-03 06:21 UTC, capedcrusader11 commented on server/router/auth.js
> +        return res.status(400).json({error: "plz filled the data"})
A simpler error message would be better "Empty fields" or "Invalid Input"

2023-03-09 12:47 UTC, aAnurag7 commented on server/DB/connection.js
> +
resolve<[94e14e9]>(https://github.com/aAnurag7/todoList/pull/4/commits/94e14e927d5a0e1600f35413c6a2fc5f5c1a840c)

2023-03-09 12:51 UTC, aAnurag7 commented on server/model/userSchema.js
> +  next();
resolve in <[14bee6a]>(https://github.com/aAnurag7/todoList/pull/4/commits/14bee6a2fc5863b0cb23782cf621ee36ce0f2787)

2023-03-09 12:52 UTC, aAnurag7 commented on server/index.js
> +app.post('/user/create',(req,res)=>{
resolve in <[14bee6a](https://github.com/aAnurag7/todoList/pull/4/commits/14bee6a2fc5863b0cb23782cf621ee36ce0f2787)>

2023-03-09 12:53 UTC, aAnurag7 commented on server/router/auth.js
> +})
resolve in <[23699f1](https://github.com/aAnurag7/todoList/pull/4/commits/23699f189d019dca5307c17dd73fd9509a94bd83)>

2023-03-09 12:53 UTC, aAnurag7 commented on server/DB/connection.js
> +const dotenv = require('dotenv')
resolve in< [23699f1](https://github.com/aAnurag7/todoList/pull/4/commits/23699f189d019dca5307c17dd73fd9509a94bd83)>

2023-03-09 12:58 UTC, aAnurag7 commented on server/DB/connection.js
> +}).then(()=>{
resolve in <[7ab9a3d]>(https://github.com/aAnurag7/todoList/pull/4/commits/7ab9a3d9920b5813a4e691f2acc0997932b7f24d)

2023-03-09 13:02 UTC, aAnurag7 commented on server/router/auth.js
> +        return res.status(422).json({err :'plz fill detail properly'})
this will send to client side , where it will check that if status is 200 or not then what to show error message or data

2023-03-09 13:06 UTC, aAnurag7 commented on server/router/auth.js
> +        return res.status(400).json({error: "plz filled the data"})
resolved in <[23699f1]>(https://github.com/aAnurag7/todoList/pull/4/commits/23699f189d019dca5307c17dd73fd9509a94bd83)

2023-03-09 13:42 UTC, aAnurag7 commented on server/config.env
> +DATABASE="mongodb+srv://anurag:anuragchatur@cluster0.r9fqxa8.mongodb.net/?retryWrites=true&w=majority"
resolve in <[4c8385b]>(https://github.com/aAnurag7/todoList/pull/4/commits/4c8385b03f0cb9e69bd3595d708bc68c7a0aebdb)

2023-03-10 11:20 UTC, UrAvgDeveloper approved these changes

2023-03-10 12:27 UTC, merged